### ISSUE TITLE
NullReferenceException in VAB

### ISSUE THREAD

**Issue by TheRealElysium** [nav0t/DecouplerShroud#1]
`[LOG 02:52:45.366] Std dev for smoothing: 3 voxel total vol: 0.520383015116331 filled vol: 0.366359180381173

[LOG 02:52:45.397] Voxelization Time (ms): 231
[LOG 02:52:54.964] HeatShield0 added to ship - part count: 4
[EXC 02:52:54.973] NullReferenceException: Object reference not set to an instance of an object
	DecouplerShroud.ModuleDecouplerShroud.detectSize ()
	DecouplerShroud.ModuleDecouplerShroud.partReattached ()
	Part.onAttach (.Part parent, Boolean first)
	EditorLogic.attachPart (.Part part, .Attachment attach)
	EditorLogic.<SetupFSM>m__8D ()
	KerbalFSM.RunEvent (.KFSMEvent evt)
	KerbalFSM.updateFSM (KFSMUpdateMode mode)
	KerbalFSM.UpdateFSM ()
	EditorLogic.Update ()
[LOG 02:53:15.029] Updating Untitled Space Craft
[LOG 02:53:15.078] Updating Untitled Space Craft
[LOG 02:53:15.131] Voxel Element CrossSection Area: 0.000269432849891823`

Getting a lot of this, just started happening recently, no idea what prompted it. Happens with various parts, in this instance I was attempting to attach a 0.625m heatshield to a custom command pod, but once it does happen it appears to happen with any of the decoupler shroud capable parts such as the T18  stack decoupler. Using v0.2

[KSP.log](https://github.com/nav0t/DecouplerShroud/files/1727147/KSP.log)

**Comment by nav0t** [comment]
Does the custom command pod have both a top and a bottom stack node?

That is something that I forgot to check completely for null pointers, it would explain the behaviour

Edit: I just realized that what I mentioned is an issue of the current version, not 0.2, I will do some further testing to figure out what caused your issue

**Comment by nav0t** [comment]
I have not been able to reproduce this. Can you have a look if you can reproduce it with the current version GitHub version, and if you can, check if it only happens with that command pod?

**Comment by TheRealElysium** [comment]
Current version https://github.com/nav0t/DecouplerShroud/commit/541e380170f52b223bbd0db01f75df572bf0b9f3
appears to have fixed this issue. Was not able to reproduce the issue after updating.  I will let you know if it happens again.

If you were curious what pod I was using it was the AES pod from Umbra Space Industries.

Thank you for this wonderful mod by the way, I was just thinking I needed something exactly like this the other week.
