### ISSUE TITLE
Wrong target framework version

### ISSUE THREAD

**Issue by HebaruSan** [nav0t/DecouplerShroud#6]
KSP mods should have `v3.5` here:

https://github.com/nav0t/DecouplerShroud/blob/713ac229991b0f51dbad59a57f4100a268f80047/Sources/DecouplerShroud/DecouplerShroud.csproj#L12

Originally reported by forum user Tonka Crash at https://forum.kerbalspaceprogram.com/index.php?/topic/183869-mods-with-wrong-net-target-framework/

**Comment by nav0t** [comment]
Thanks for pointing it out. Fixed the issue in the latest commit
