### ISSUE TITLE
Shroud misaligned after loading a vessel already in orbit

### ISSUE THREAD

**Issue by Gordon-Dry** [nav0t/DecouplerShroud#8]
Pic:
![screenshot_2019-06-18--01-13-37](https://user-images.githubusercontent.com/29145213/59642781-b9b74c00-9166-11e9-8abc-09afba6a1270.png)

Log and stuff:
https://www.dropbox.com/s/tupilrxxt3s7j8o/output_log.txt%20and%20stuff%202019-06-18-01.zip?dl=1

**Comment by Gordon-Dry** [comment]
I did not use a "go to" feature from KAC or Kerbalism, I loaded the vessel from tracking station.

**Comment by nav0t** [comment]
I've not been able to reconstruct this. Do you have a way to reconstruct this issue (with stock parts if possible)? Does this always happen if you load this vessel? If you launch the same vessel again, does it happen too?

**Comment by Gordon-Dry** [comment]
The last two times I launched this (slightly edited but with same decoupler + shroud) it did not happen.

I will close this for now.
